### ISSUE TITLE
Mention built-in strip functionality in Cargo?

### ISSUE THREAD

**Issue by johnthagen** [guedou/cargo-strip#10]
This PR will soon land and become stabilized making it possible to have Cargo automatically strip binaries natively. It may be worth pointing users to this:

- https://github.com/rust-lang/cargo/pull/10088

**Comment by guedou** [comment]
Thanks for reaching me, and please accept my apologies for this late reply. These past weeks have been exhausting personally and professionally.

Would you mind doing a PR?

Also, so you think that this new cargo feature will require me to deprecate this project?

Thanks

**Comment by johnthagen** [comment]
@guedou The new functionality can be seen here
- https://github.com/johnthagen/min-sized-rust/pull/34

It will only be available in 1.59+ so for a time I could see users still wanting to use `cargo-strip`. I think long term it could probably be deprecated though.

**Comment by johnthagen** [comment]
I would say we wait for Rust 1.59 to be released, and then we could mention it in the README as there will be a link to stable docs available that has it.

**Comment by guedou** [comment]
It looks like that it is time to update the README!

**Comment by guedou** [comment]
@johnthagen what do you think of the following PR https://github.com/guedou/cargo-strip/pull/13 ?

**Comment by johnthagen** [comment]
@guedou Looks great!

**Comment by guedou** [comment]
Thanks for you prompt review!
