### ISSUE TITLE
Add a clearer description

### ISSUE THREAD

**Issue by heisen-li** [guedou/cargo-strip#12]
Thank you for your work. What is the information about the divestiture?Why has so much content been reduced?
My binaries are down 3232k.

**Comment by heisen-li** [comment]
In addition, if the stripped information includes a symbol table, should the stripped information be stored in a file?

**Comment by guedou** [comment]
I do not think that it is possible using the `strip` command. I will suggest that you run dump it with a tool like `objdump` before calling `cargo strip` .
